import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/context/CartContext";
import { Toaster } from "react-hot-toast";

// Load fonts from Google
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// App metadata (optional for SEO or head elements)
export const metadata = {
  title: "BraBliss",
  description: "Generated by create next app",
};

// Main layout function
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased">
        {/* Toast notification system */}
        <Toaster position="top-center" toastOptions={{ duration: 3000 }} />

        {/* Global cart context provider */}
        <CartProvider>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
