import "./globals.css";
import { CartProvider } from "@/context/CartContext";
import { Toaster } from "react-hot-toast";

// Load fonts from Google

// App metadata (optional for SEO or head elements)
export const metadata = {
  title: "BraBliss",
  description: "Generated by create next app",
};

// Main layout function
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        {/* Toast notification system */}
        <Toaster position="top-center" toastOptions={{ duration: 3000 }} />

        {/* Global cart context provider */}
        <CartProvider>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
